"""Real-data ingestion track (isolated — does NOT touch the production demo).

Reads a raw credit CSV, maps its columns to the CreditFlow canonical schema
using a mapping config (pipeline/data/mapping.yaml), normalizes the target,
reports missing/duplicate/out-of-range issues, writes a processed dataset, and
emits a manifest with a SHA-256 for provenance.

Migration safety:
- The PRODUCTION demo continues to use data/creditflow_dataset.csv (synthetic
  proxy) generated by generate_dataset.py. This module writes ONLY to
  data/processed/ + data/metadata/ and NEVER retrains / replaces the model.
- All reports are honest: unmapped / semantically-different source columns are
  flagged, not silently filled.

Usage:
    python -m pipeline.data.ingest \\
        --config pipeline/data/mapping.yaml \\
        --raw path/to/raw.csv \\
        --out data/processed/creditflow_real.csv \\
        --meta data/metadata/dataset_manifest.json
"""
from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from pipeline.validation.schemas import CANONICAL_COLUMNS, TARGET_COLUMN, validate_dataframe  # noqa: E402


def _load_yaml(path: Path) -> dict:
    """Load a mapping YAML (yaml is an optional dep; fall back to json)."""
    if not path.exists():
        raise FileNotFoundError(f"Mapping config not found: {path}")
    try:
        import yaml
    except ImportError:
        raise ImportError(
            "PyYAML is required for ingest. Install: pip install pyyaml  "
            "(it is optional so requirements.txt stays lean)."
        )
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _coerce_numeric(series: pd.Series, name: str) -> pd.Series:
    """Best-effort numeric coercion; non-numeric values become NA."""
    try:
        return pd.to_numeric(series, errors="coerce")
    except Exception:  # pragma: no cover
        return pd.Series(pd.NA, index=series.index, name=name)


def ingest(
    raw_path: Path,
    config_path: Path,
    processed_path: Path,
    manifest_path: Path,
    source_name: str | None = None,
) -> dict:
    """Run the mapping/validation ingest and write processed + manifest."""
    config = _load_yaml(config_path)
    cfg = config["dataset"]
    target_cfg = config["target"]
    features_cfg = config["features"]
    dropped_cfg = config.get("dropped_columns", [])

    raw = pd.read_csv(raw_path)
    report_missing_source: list[str] = []

    # --- build the canonical output frame via the mapping layer ---
    out = pd.DataFrame()
    canonical_present: dict[str, bool] = {}
    for canonical, source in features_cfg.items():
        if source is None or source not in raw.columns:
            if source is not None and source not in raw.columns:
                report_missing_source.append(source)
            canonical_present[canonical] = False
            out[canonical] = pd.NA
        else:
            canonical_present[canonical] = True
            out[canonical] = _coerce_numeric(raw[source], canonical)

    # --- target normalization from the source label column ---
    src_target = target_cfg["source_column"]
    if src_target in raw.columns:
        label_map = {str(k): int(v) for k, v in target_cfg["mapping"].items()}
        out[target_cfg["output_column"]] = (
            raw[src_target].astype(str).map(label_map).astype("Int64")
        )
    else:
        out[target_cfg["output_column"]] = pd.NA

    # --- basic canonical validation (best-effort; reports, does not fail) ---
    out_df = out.dropna(subset=[c for c in CANONICAL_COLUMNS], how="all")
    _, violations = validate_dataframe(out_df.drop(columns=[TARGET_COLUMN], errors="ignore"))

    # --- persist processed + manifest ---
    processed_path.parent.mkdir(parents=True, exist_ok=True)
    out_df.to_csv(processed_path, index=False)
    sha = sha256_file(processed_path)

    pos_rate = None
    labels = out_df[TARGET_COLUMN].dropna()
    if len(labels) > 0:
        pos_rate = float(labels.astype(int).mean())

    dropped = [d.get("name", d) for d in dropped_cfg if isinstance(d, dict)]
    missing_flags = [c for c, present in canonical_present.items() if not present]
    mapped_sources = {s for s in features_cfg.values() if s is not None}
    dropped_names = {d.get("name", d) for d in dropped_cfg if isinstance(d, dict)}
    unmapped_raw = sorted(
        set(raw.columns) - mapped_sources - dropped_names - {target_cfg["source_column"]}
    )
    try:
        processed_rel = str(processed_path.resolve().relative_to(ROOT))
    except ValueError:  # output outside the repo (e.g. tmp dir in tests)
        processed_rel = str(processed_path)
    manifest = {
        "dataset": cfg["name"],
        "version": cfg["version"],
        "source": cfg["source"],
        "source_name": source_name or str(raw_path),
        "config": str(config_path.relative_to(ROOT)),
        "rows": int(len(out_df)),
        "raw_rows": int(len(raw)),
        "columns": int(out_df.shape[1]),
        "target": TARGET_COLUMN,
        "positive_rate": None if pos_rate is None else round(pos_rate, 4),
        "sha256": sha,
        "missing_source_columns": sorted(d for d in report_missing_source),
        "missing_canonical_columns": sorted(missing_flags),
        "dropped_columns": sorted(dropped),
        "unmapped_raw_columns": unmapped_raw,
        "validation_violations": violations,
        "ready_for_training": len(violations) == 0,
        "ingested_at": _dt.datetime.now(_dt.timezone.utc).isoformat(),
        "processed_path": processed_rel,
    }
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, indent=2))
    return manifest


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="CreditFlow real-data ingest (isolated).")
    ap.add_argument("--config", default=str(ROOT / "pipeline" / "data" / "mapping.yaml"))
    ap.add_argument("--raw", default=None, help="Path to the raw dataset CSV (required unless --synthetic-demo).")
    ap.add_argument("--out", default=str(ROOT / "data" / "processed" / "creditflow_real.csv"))
    ap.add_argument("--meta", default=str(ROOT / "data" / "metadata" / "dataset_manifest.json"))
    ap.add_argument("--name", default=None, help="Dataset name override for the manifest.")
    ap.add_argument(
        "--synthetic-demo",
        action="store_true",
        help="Generate the synthetic proxy demo CSV (no real data needed).",
    )
    args = ap.parse_args(argv)

    if args.synthetic_demo:
        from pipeline.data.generate_dataset import write_dataset
        demo = ROOT / "data" / "creditflow_dataset.csv"
        write_dataset(demo, n=5000, random_state=42)
        print(f"[demo] synthetic proxy dataset -> {demo}")
        print(f"[demo] sha256={sha256_file(demo)}")
        return 0

    if not args.raw:
        ap.error("--raw is required unless --synthetic-demo is used")

    manifest = ingest(
        Path(args.raw), Path(args.config), Path(args.out), Path(args.meta), source_name=args.name
    )
    print(json.dumps(manifest, indent=2))
    print(f"\n[ingest] processed -> {args.out}")
    print(f"[ingest] manifest   -> {args.meta}")
    print(f"[ingest] ready_for_training = {manifest['ready_for_training']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())